import Head from 'next/head'
import { Header } from '@/components/Header'
import { SideBar } from '@/components/SideBar'
import matter from 'gray-matter'
import { serialize } from 'next-mdx-remote/serialize'
import { MDXRemote, MDXRemoteSerializeResult } from 'next-mdx-remote'
import * as fs from "fs";

interface HomeProps {
  mdxSource: MDXRemoteSerializeResult;
}

export default function Home({ mdxSource }: HomeProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full bg-[#603d41]">
      <div id="container" className="w-full h-full bg-[#603d41]">
        <Header />
        <main className="px-6 pt-4 md:px-12 lg:pt-8 pb-12">
          <div className="flex flex-col lg:flex-row">
            <div id="main-content" className="flex-grow lg:mr-12">
              <MDXRemote {...mdxSource} />
            </div>
            <SideBar />
          </div>
        </main>
      </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const markdownWithMeta = fs.readFileSync('src/pages/sample.mdx', 'utf8');
  const { data: frontMatter, content } = matter(markdownWithMeta)
  const mdxSource = await serialize(content)
  return {
    props: {
      mdxSource
    },
  }
}